/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_keinesorgen_tts_Tts */

#ifndef _Included_net_keinesorgen_tts_Tts
#define _Included_net_keinesorgen_tts_Tts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_keinesorgen_tts_Tts
 * Method:    say
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lnet/keinesorgen/tts/SayResult;
 */
JNIEXPORT jobject JNICALL Java_net_keinesorgen_tts_Tts_say
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
